name = "messages-api"
main = "src/app.js"
node_compat = true
compatibility_date = "2024-11-11"
workers_dev = true
API_KEY = "f-POJIkm9G9zO9rwHRT5VIUMQoqQsvVAM_ROIbqW“
account_id = "2bd2e037a56bddc2449360092b62cc21"
zone_id = "22fc705c7ea57686226166a935e2e88c"
[build]
command = "npm run build"
[build.upload]
format = "service-worker"
[site]
bucket = "./public"  # 存放静态资源的目录